### ISSUE TITLE
Unsupported major.minor version

### ISSUE THREAD

**Issue by zplesac** [Raizlabs/Griddle#2]
After upgrading to Android Studio 1.1. RC 1, an error is occurring while syncing with Gradle files:

Error:(3, 0) Cause: com/raizlabs/GriddlePlugin : Unsupported major.minor version 52.0

I'm using Griddle version 1.0.2.

**Comment by ianrumac** [comment]
Getting the same error here, using Griddle 1.0.2 and using 1.0.0, also Android Studio 1.1 RC 1.

**Comment by agrosner** [comment]
@zplesac thanks for reporting this. can you send me more info, such as:
1.  ./gradlew --refresh-dependencies --stacktrace 
2. If the dependency has that version 52.0 or what your build.gradle looks like.

thanks!

**Comment by bkromhout** [comment]
I'm also seeing this issue. Just so you know, whenever I've seen the message "Unsupported major.minor version 52.0" on anything, it's been when something being built with jdk 1.7 is attempting to use a library compiled with jdk 1.8. Did you maybe compile something in Griddle with jdk 8? Either way, here's my stack trace using the commands you asked for (name, app directory name, and app name removed): http://pastebin.com/DRQBSDcM

**Comment by agrosner** [comment]
@bkromhout certainly possible. I am using jdk1.8 on my computer, so If I change it to JDK 7 compiler, I think this issue will resolve itself.

**Comment by bkromhout** [comment]
I assume that will be the case.

**Comment by agrosner** [comment]
@bkromhout thank you for more help on this. I should try to get this issue resolved by tomorrow afternoon.

**Comment by bkromhout** [comment]
No problem, I'll test it out once the recompiled version is up.

**Comment by mayuroks** [comment]
I am using Java 7 on ubuntu 14.04

``` bash
/usr/lib/jvm/java-7-oracle/bin/java -version                                                              
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```

still got the error

``` bash
com/raizlabs/GriddlePlugin : Unsupported major.minor version 52.0
```

tried running gradlew with --stacktrace but the command was taking just too long to complete

**Comment by agrosner** [comment]
Ill close it if the test passes @mayuroks @zplesac

**Comment by agrosner** [comment]
try 1.0.3

**Comment by bkromhout** [comment]
Works great for me now.

**Comment by agrosner** [comment]
Thanks @bkromhout !! it was the fact that the plugin left out:

``` groovy
sourceCompatibility = 1.5
```

so the assumed source compatibility was 1.8 of my machine. oops
